package com.example.notesplugin.presentation.util

enum class CodeLanguage(val displayName: String, val fileExtension: String) {
    KOTLIN("Kotlin", "kt"),
    JAVA("Java", "java"),
    PYTHON("Python", "py"),
    JAVASCRIPT("JavaScript", "js"),
    TYPESCRIPT("TypeScript", "ts"),
    HTML("HTML", "html"),
    CSS("CSS", "css"),
    SCSS("SCSS", "scss"),
    JSON("JSON", "json"),
    XML("XML", "xml"),
    YAML("YAML", "yml"),
    MARKDOWN("Markdown", "md"),
    SQL("SQL", "sql"),
    SHELL("Shell", "sh"),
    BASH("Bash", "bash"),
    C("C", "c"),
    CPP("C++", "cpp"),
    CSHARP("C#", "cs"),
    RUST("Rust", "rs"),
    GO("Go", "go"),
    RUBY("Ruby", "rb"),
    PHP("PHP", "php"),
    SWIFT("Swift", "swift"),
    OBJECTIVE_C("Objective-C", "m"),
    PERL("Perl", "pl"),
    LUA("Lua", "lua"),
    GROOVY("Groovy", "groovy"),
    DART("Dart", "dart"),
    HASKELL("Haskell", "hs"),
    SCALA("Scala", "scala"),
    R("R", "r")
}